<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BookSeeder extends Seeder
{
    public function run(): void
    {

        DB::table('books')->insert([
            [
                'title' => '1001 Khasiat & Manfaat Jamu Godog; Untuk Segala Macam Penyakit',
                'author' => 'Faisal M. Sakri',
                'publisher' => 'Diandra Kreatif',
                'year' => 2022,
                'isbn' => '978-602-19081-4-3',
                'ukuran' => '13 x 19',
                'jumlah_halaman' => 82,
                'color' => 'bw',
                'stock' => 2,
                'price' => 50756,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => '19 Jenis Kelinci Paling Populer',
                'author' => 'Erlita Mega',
                'publisher' => 'Rumah Baca',
                'year' => 2023,
                'isbn' => '978-623-8247-21-9',
                'ukuran' => '14 x 21',
                'jumlah_halaman' => 56,
                'color' => 'bw',
                'stock' => 2,
                'price' => 44256,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => '25 Menu Spesial Si Kecil',
                'author' => 'Anti Apriliyanti Suganti',
                'publisher' => 'Mutiara Allamah Utama',
                'year' => 2023,
                'isbn' => '978-602-14115-5-1',
                'ukuran' => '19 x 23',
                'jumlah_halaman' => 52,
                'color' => 'color',
                'stock' => 2,
                'price' => 69856,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => '25 Resep Camilan Spesial Favorit',
                'author' => 'Anti Apriliyanti Suganti',
                'publisher' => 'Mutiara Allamah Utama',
                'year' => 2023,
                'isbn' => '978-602-14115-4-4',
                'ukuran' => '19 x 23',
                'jumlah_halaman' => 52,
                'color' => 'color',
                'stock' => 2,
                'price' => 69856,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => '30 Menit Memasak Masakan Padang',
                'author' => 'Tim Dapur Anggrek',
                'publisher' => 'Pustaka Anggrek',
                'year' => 2022,
                'isbn' => '9789792499155',
                'ukuran' => '14 x 20,5',
                'jumlah_halaman' => 24,
                'color' => 'bw',
                'stock' => 2,
                'price' => 45756,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => '30 Menit Sarapan Pagi Berbahan Nasi',
                'author' => 'Tim Dapur Anggrek',
                'publisher' => 'Pustaka Anggrek',
                'year' => 2022,
                'isbn' => '9789792499056',
                'ukuran' => '14 x 20,5',
                'jumlah_halaman' => 28,
                'color' => 'bw',
                'stock' => 2,
                'price' => 47256,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'title' => '30 Variasi Olahan Mi Instan',
                'author' => 'Nining P. & Anti Apriliyanti',
                'publisher' => 'Media Pressindo',
                'year' => 2022,
                'isbn' => '979-788-145-8',
                'ukuran' => '19 x 19 cm',
                'jumlah_halaman' => 32,
                'color' => 'bw',
                'stock' => 2,
                'price' => 53056,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Aku Mau Memaafkan',
                'author' => 'Anee Rahmaan',
                'publisher' => 'Bee Media',
                'year' => 2020,
                'isbn' => '978-602-6587-85-5',
                'ukuran' => '20 x 20 cm',
                'jumlah_halaman' => 24,
                'color' => 'color',
                'stock' => 2,
                'price' => 45756,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Akuamber Akuaponik Di Ember',
                'author' => 'B. Prasetya',
                'publisher' => 'Penebar Swadaya',
                'year' => 2020,
                'isbn' => '9786232251007',
                'ukuran' => '15 x 21',
                'jumlah_halaman' => 58,
                'color' => 'bw',
                'stock' => 2,
                'price' => 30156,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'title' => 'Aneka Kreasi Dari Stik Es Krim',
                'author' => 'Kak Derosya',
                'publisher' => 'Laksana',
                'year' => 2019,
                'isbn' => '978-602-407-621-4',
                'ukuran' => '14 x 20 cm',
                'jumlah_halaman' => 68,
                'color' => 'color',
                'stock' => 2,
                'price' => 46556,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Berhenti Mencemaskan Hidupmu',
                'author' => 'Sabrina Jasmine',
                'publisher' => 'Cv. Shinyuu Japanindo',
                'year' => 2022,
                'isbn' => '978-623-98752-6-8',
                'ukuran' => '14 x 20',
                'jumlah_halaman' => 106,
                'color' => 'bw',
                'stock' => 2,
                'price' => 58856,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Beternak Kambing',
                'author' => 'Tim Agro Mandiri',
                'publisher' => 'Visi Mandiri',
                'year' => 2018,
                'isbn' => '9786023170777',
                'ukuran' => '14 x 21',
                'jumlah_halaman' => 86,
                'color' => 'bw',
                'stock' => 2,
                'price' => 67756,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Budi Daya Gurame Agar Cepat Besar',
                'author' => 'Abdul Qolik',
                'publisher' => 'Hijaz Pustaka Mandiri',
                'year' => 2022,
                'isbn' => '978-602-51556-4-2',
                'ukuran' => '14 x 21 cm',
                'jumlah_halaman' => 96,
                'color' => 'bw',
                'stock' => 2,
                'price' => 54756,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'title' => 'Budi Daya Jahe Merah Organik Yang Menguntungkan',
                'author' => 'Lulu Hamidah',
                'publisher' => 'Salma Idea',
                'year' => 2022,
                'isbn' => '978-602-70501-7-4',
                'ukuran' => '14 x 21 cm',
                'jumlah_halaman' => 120,
                'color' => 'bw',
                'stock' => 2,
                'price' => 54756,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Budidaya Dan Bisnis Jamur Tiram Secara Tradisional & Modern',
                'author' => 'Yusnu Iman Nurhakim',
                'publisher' => 'Bci Media',
                'year' => 2022,
                'isbn' => '978-602-6724-46-5',
                'ukuran' => '15 x 23 cm',
                'jumlah_halaman' => 88,
                'color' => 'bw',
                'stock' => 2,
                'price' => 58856,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Budidaya Dan Bisnis Lele Dalam Kolam Terpal',
                'author' => 'Ki Agus Angga',
                'publisher' => 'Bci Media',
                'year' => 2022,
                'isbn' => '978-602-6724-43-4',
                'ukuran' => '15 x 23 cm',
                'jumlah_halaman' => 78,
                'color' => 'bw',
                'stock' => 2,
                'price' => 58856,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'title' => 'Buku Pintar Emak : 30 Mpasi Terbaik',
                'author' => 'Mita Aeera',
                'publisher' => 'Senja Publishing',
                'year' => 2023,
                'isbn' => '978-602-6563-91-0',
                'ukuran' => '24 x 19',
                'jumlah_halaman' => 72,
                'color' => 'color',
                'stock' => 2,
                'price' => 100156,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Cara Cerdas Budidaya Jahe: Panen Maksimal',
                'author' => 'Keen Achrori',
                'publisher' => 'Trans Idea Publishing',
                'year' => 2018,
                'isbn' => '978-602-0808-99-4',
                'ukuran' => '14,8 x 21 cm',
                'jumlah_halaman' => 120,
                'color' => 'bw',
                'stock' => 2,
                'price' => 57156,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Cara Membuat Teh Herbal',
                'author' => 'Panuwun Budi',
                'publisher' => 'Rumah Baca',
                'year' => 2023,
                'isbn' => '978-623-8247-61-5',
                'ukuran' => '14 x 21',
                'jumlah_halaman' => 56,
                'color' => 'bw',
                'stock' => 2,
                'price' => 44256,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Dahsyatnya Percaya Diri',
                'author' => 'Chibita Wiranegara',
                'publisher' => 'Cv Indoliterasi',
                'year' => 2022,
                'isbn' => '978-602-5644-48-1',
                'ukuran' => '14 x 20',
                'jumlah_halaman' => 100,
                'color' => 'bw',
                'stock' => 2,
                'price' => 50756,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Diary Kuliah Dobel',
                'author' => 'Dinna Andianny',
                'publisher' => 'Stiletto Indie Book',
                'year' => 2021,
                'isbn' => '978-602-336-942-3',
                'ukuran' => '13 x 19',
                'jumlah_halaman' => 120,
                'color' => 'bw',
                'stock' => 2,
                'price' => 46556,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'title' => 'Ensikidz Dunia Hewan : Serangga',
                'author' => 'Wahyu Azmi',
                'publisher' => 'Visi Mandiri',
                'year' => 2022,
                'isbn' => '9786236213131',
                'ukuran' => '20 x 20',
                'jumlah_halaman' => 24,
                'color' => 'color',
                'stock' => 2,
                'price' => 41856,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Hari Minggu Bersama Ibu',
                'author' => 'Anee Rahman',
                'publisher' => 'Bee Media',
                'year' => 2019,
                'isbn' => '978-602-6587-72-5',
                'ukuran' => '20 x 20 cm',
                'jumlah_halaman' => 28,
                'color' => 'color',
                'stock' => 2,
                'price' => 45756,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Ihsan Kepada Diri Sendiri - Aku Mencintai Diriku',
                'author' => 'Mamichila',
                'publisher' => 'Ziyadbooks',
                'year' => 2022,
                'isbn' => '9786023177684',
                'ukuran' => '20 x 20',
                'jumlah_halaman' => 24,
                'color' => 'color',
                'stock' => 2,
                'price' => 38556,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Jadi Penyiar Itu Asyik Lho ! (Revisi)',
                'author' => 'Asep Syamsul M. Romli',
                'publisher' => 'Nuansa Cendekia',
                'year' => 2021,
                'isbn' => '978-602-8394-93-2',
                'ukuran' => '14,5 x 21',
                'jumlah_halaman' => 136,
                'color' => 'bw',
                'stock' => 2,
                'price' => 51556,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Juragan Pisang',
                'author' => 'Irwan Kelana',
                'publisher' => 'Al Mawardi Prima',
                'year' => 2020,
                'isbn' => '978-602-5858-18-5',
                'ukuran' => '13 x 19 cm',
                'jumlah_halaman' => 60,
                'color' => 'bw',
                'stock' => 2,
                'price' => 43556,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'title' => 'Jurus Sukses Menjadi Eterpreneur Makmur',
                'author' => 'Yulian Harsono',
                'publisher' => 'Pintar Pustaka',
                'year' => 2021,
                'isbn' => '978-602-51394-7-5',
                'ukuran' => '14 cm x 21 cm',
                'jumlah_halaman' => 100,
                'color' => 'bw',
                'stock' => 2,
                'price' => 66856,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Kiat Membangun Bank Sampah Dan Cara Pengelolaannya',
                'author' => 'Sri Lestari',
                'publisher' => 'Hijaz Pustaka Mandiri',
                'year' => 2022,
                'isbn' => '978-602-5790-56-0',
                'ukuran' => '14 x 20 cm',
                'jumlah_halaman' => 122,
                'color' => 'bw',
                'stock' => 2,
                'price' => 58856,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Kiat Sukses Bertanam Hidroponik Untuk Pemula',
                'author' => 'Susi Anggraeni',
                'publisher' => 'Trans Idea Publishing',
                'year' => 2018,
                'isbn' => '978-602-0808-98-7',
                'ukuran' => '14,8 x 21 cm',
                'jumlah_halaman' => 120,
                'color' => 'bw',
                'stock' => 2,
                'price' => 57156,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Mengintip Peluang Bisnis Budidaya Sayur Organik',
                'author' => 'Keen Achrori',
                'publisher' => 'Trans Idea Publishing',
                'year' => 2018,
                'isbn' => '978-602-5687-13-6',
                'ukuran' => '14,8 x 21 cm',
                'jumlah_halaman' => 120,
                'color' => 'bw',
                'stock' => 2,
                'price' => 57156,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Menuju Desa Siaga Bencana',
                'author' => 'Eva Nurdinawati',
                'publisher' => 'Hijaz Pustaka Mandiri',
                'year' => 2021,
                'isbn' => '978-602-5790-52-2',
                'ukuran' => '14 x 20 cm',
                'jumlah_halaman' => 122,
                'color' => 'bw',
                'stock' => 2,
                'price' => 61156,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'title' => 'Menyelami Diri Sendiri Tanpa Rasa Takut',
                'author' => 'Melinda',
                'publisher' => 'Mirra Buana Media',
                'year' => 2023,
                'isbn' => '978-623-323-294-4',
                'ukuran' => '14 x 20',
                'jumlah_halaman' => 98,
                'color' => 'bw',
                'stock' => 2,
                'price' => 50756,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Ngomong Bahasa Inggris Itu Mudah & Gampang',
                'author' => 'Fitri Rahmawati',
                'publisher' => 'Bci Media',
                'year' => 2022,
                'isbn' => '978-602-6724-49-6',
                'ukuran' => '13 x 19 cm',
                'jumlah_halaman' => 128,
                'color' => 'bw',
                'stock' => 2,
                'price' => 58856,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


        ]);
    }
}
